# Generated by Django 5.2.8 on 2025-12-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataTable',
        ),
    ]
